import { NextRequest, NextResponse } from 'next/server'
import { getPanelActor } from '@/lib/api-auth'
import { and, desc, eq } from 'drizzle-orm'
import { db, ensurePanelSchema } from '@/lib/db'
import { agentCommands, backups, serverPermissions, servers, worlds } from '@/lib/db/schema'


async function actor(){return getPanelActor()}
async function access(serverId:string,a:NonNullable<Awaited<ReturnType<typeof actor>>>){const server=(await db.select().from(servers).where(eq(servers.id,serverId)).limit(1))[0];if(!server)return null;if(a.role==='manager'||server.userId===a.id)return {server,permission:null,manager:true};const permission=(await db.select().from(serverPermissions).where(and(eq(serverPermissions.serverId,serverId),eq(serverPermissions.userId,a.id))).limit(1))[0];return permission?{server,permission,manager:false}:null}
function canViewBackups(result:NonNullable<Awaited<ReturnType<typeof access>>>){if(result.manager)return true;const sections=Array.isArray(result.permission?.sections)?result.permission.sections:[];return !!result.permission?.canBackup||sections.includes('backups')}


export async function GET(request:NextRequest){await ensurePanelSchema();const a=await actor();if(!a)return NextResponse.json({error:'Unauthorized'},{status:401});if(!a.approved)return NextResponse.json({error:'Approval required'},{status:403});const serverId=request.nextUrl.searchParams.get('serverId');if(!serverId)return NextResponse.json({error:'serverId gerekli'},{status:400});const result=await access(serverId,a);if(!result||!canViewBackups(result))return NextResponse.json({error:'Forbidden'},{status:403});const rows=await db.select({id:backups.id,worldId:backups.worldId,blobPathname:backups.blobPathname,sizeMb:backups.sizeMb,sizeBytes:backups.sizeBytes,createdAt:backups.createdAt,worldName:worlds.name}).from(backups).innerJoin(worlds,eq(backups.worldId,worlds.id)).where(and(eq(worlds.serverId,serverId),eq(backups.userId,result.server.userId))).orderBy(desc(backups.createdAt)).limit(100);return NextResponse.json({backups:rows},{headers:{'Cache-Control':'private, no-store'}})}


export async function POST(request:NextRequest){await ensurePanelSchema();const a=await actor();if(!a)return NextResponse.json({error:'Unauthorized'},{status:401});if(!a.approved)return NextResponse.json({error:'Approval required'},{status:403});const body=await request.json();const serverId=String(body.serverId||'');const result=await access(serverId,a);if(!result||( !result.manager&&!result.permission?.canBackup))return NextResponse.json({error:'Yedek işlemi için yetkiniz yok'},{status:403});const type=String(body.type||'backup');const allowed=['backup','backup-verify','backup-copy','restore-backup','delete-backup'];if(!allowed.includes(type))return NextResponse.json({error:'Geçersiz backup işlemi'},{status:400});if((type==='restore-backup'||type==='delete-backup')&&body.confirm!==true)return NextResponse.json({error:'Onay gerekli'},{status:400});const [command]=await db.insert(agentCommands).values({userId:result.server.userId,nodeId:result.server.nodeId,serverId,type,payload:{path:body.path,label:body.label||'manual',kind:body.kind||'full',confirm:body.confirm===true},status:'queued'}).returning();return NextResponse.json({ok:true,command},{status:202})}