'use client'
import { useState } from 'react'
import useSWR from 'swr'
import { Activity, Archive, Ban, CheckCircle2, Database, FileText, FolderCog, Gamepad2, HardDrive, KeyRound, Network, Play, RefreshCw, ShieldCheck, Terminal, UserCog, Wrench } from 'lucide-react'
import { Button } from '@/components/ui/button'
import { useActionConfirm } from '@/components/action-confirm-dialog'

type Item={label:string;action:string;icon?:any;danger?:boolean;note?:string;payload?:Record<string,unknown>}
const groups:Record<string,{title:string;text:string;items:Item[]}[]>={
 players:[{title:'Gelişmiş oyuncu işlemleri',text:'Detay, moderasyon, envanter ve erişim işlemleri agent kuyruğu üzerinden yürütülür.',items:[
  {label:'Oyuncu detaylarını yenile',action:'player-details',icon:UserCog},{label:'Envanter bilgisi',action:'player-inventory',icon:Archive},{label:'Ender chest bilgisi',action:'player-enderchest',icon:Archive},{label:'Komut geçmişi',action:'player-history',icon:Terminal},{label:'Moderasyon notu',action:'player-note',icon:FileText},{label:'Ban / OP / whitelist işlemi',action:'player-action',icon:Ban,danger:true,note:'Seçili oyuncu ve işlem agent entegrasyonunda doğrulanır.'}] }],
 software:[{title:'Uyumluluk ve bakım',text:'Loader, mod ve plugin işlemlerini güvenli agent komutları olarak hazırlar.',items:[{label:'Uyumluluk taraması',action:'software-compatibility',icon:CheckCircle2},{label:'Mod/plugin tara',action:'addon-scan',icon:Wrench},{label:'Güncellemeleri kontrol et',action:'addon-update',icon:RefreshCw},{label:'Etkinleştir / devre dışı bırak',action:'addon-toggle',icon:Play}]}],
 backups:[{title:'Yedek doğrulama araçları',text:'Checksum ve kopyalama gibi işlemler ayrı agent görevleri olarak çalışır.',items:[{label:'Yedeği doğrula',action:'backup-verify',icon:ShieldCheck},{label:'Yedeği kopyala',action:'backup-copy',icon:Archive}]}],
 network:[{title:'Ağ güvenliği araçları',text:'Firewall kuralları sıfırlanmaz; yalnız mevcut durum okunur ve güvenli değişiklikler ayrı komutlarla uygulanır. SFTP yönetimi yukarıdaki özel SFTP kartından yapılır.',items:[{label:'Firewall durumunu oku',action:'firewall-status',icon:ShieldCheck},{label:'Açık portları tara',action:'port-scan',icon:Network}]}],
 databases:[{title:'Veritabanı bakım araçları',text:'Mevcut veritabanını yeniden oluşturmaz; işlemler ayrı ve denetlenebilir görevlerdir.',items:[{label:'Yedek al',action:'database-backup',icon:Archive},{label:'Restore hazırla',action:'database-restore',icon:RefreshCw,danger:true},{label:'SQL dışa aktar',action:'database-export',icon:Database},{label:'SQL içe aktar',action:'database-import',icon:Database,danger:true},{label:'Tabloları optimize et',action:'database-optimize',icon:Activity},{label:'Tablo onarımı',action:'database-repair',icon:Wrench,danger:true},{label:'Yeni kullanıcı',action:'database-user',icon:UserCog},{label:'Kullanıcı izinları',action:'database-permissions',icon:KeyRound}]}],
 logs:[{title:'Günlük kaynakları',text:'Crash, agent ve başlangıç günlükleri ayrı kaynaklar olarak istenir.',items:[{label:'Crash raporları',action:'crash-reports',icon:FileText},{label:'Agent logları',action:'agent-logs',icon:Terminal},{label:'Başlangıç logları',action:'server-startup-logs',icon:Play},{label:'Log dışa aktar',action:'logs-export',icon:Archive}]}],
 security:[{title:'Dosya güvenliği',text:'Tarama, hash ve karantina görevleri world verilerini değiştirmeden güvenli helper üzerinden çalışacak şekilde kuyruğa alınır.',items:[{label:'Tüm dosyaları tara',action:'scan-files',icon:ShieldCheck},{label:'Mods tara',action:'scan-mods',icon:Gamepad2},{label:'Plugins tara',action:'scan-plugins',icon:Wrench},{label:'Config tara',action:'scan-config',icon:FolderCog},{label:'JAR metadata kontrolü',action:'jar-metadata',icon:FileText},{label:'SHA-256 hesapla',action:'hash-files',icon:KeyRound}]},{title:'Giriş ve ağ güvenliği',text:'Giriş denemeleri, portlar ve firewall durumu gerçek agent verisiyle doldurulacak.',items:[{label:'Giriş güvenliği durumu',action:'login-security-status',icon:KeyRound},{label:'Ağ güvenliği durumu',action:'network-security-status',icon:Network},{label:'Firewall durumu',action:'firewall-status',icon:ShieldCheck},{label:'Port taraması',action:'port-scan',icon:Network}]},{title:'Anti-cheat yönetimi',text:'Loader uyumluluğu doğrulanmadan plugin/mod kurulumu yapılmaz.',items:[{label:'Anti-cheat durumunu oku',action:'anticheat-status',icon:Gamepad2},{label:'Güncelleme kontrolü',action:'anticheat-update',icon:RefreshCw},{label:'Yapılandırmayı hazırla',action:'anticheat-configure',icon:Wrench}]}]
}

async function readJson(r:Response){const t=await r.text();try{return t?JSON.parse(t):{}}catch{return {error:t}}}
export function ServerFeatureActions({serverId,section}:{serverId:string;section:string}){
 const [busy,setBusy]=useState('');const [notice,setNotice]=useState('');const [last,setLast]=useState<any>(null);const list=groups[section]??[]; const actionConfirm=useActionConfirm(); const {data:actionData}=useSWR<{supportedActions:string[]}>(`/api/server-actions?serverId=${serverId}`,async (u: string)=>{const r=await fetch(u,{cache:'no-store'});return readJson(r)}); const supportedActions=new Set(actionData?.supportedActions??[])
 if(!list.length)return null
 async function run(item:Item){if(item.danger&&!await actionConfirm.ask(`${item.label} işlemi güvenlik onayı gerektirir.`,{title:'Kritik agent işlemi',confirmLabel:'Devam et',danger:true,requiredText:item.action}))return;setBusy(item.action);setNotice('');try{const r=await fetch('/api/server-actions',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({serverId,action:item.action,payload:item.payload??{},confirm:!!item.danger})});const d=await readJson(r);if(!r.ok)throw new Error(d.error??'İşlem başlatılamadı');setLast(d.command);setNotice(`${item.label} agent kuyruğuna alındı.`)}catch(e){setNotice(e instanceof Error?e.message:'İşlem başarısız')}finally{setBusy('')}}
 return <div className="space-y-3">{actionConfirm.dialog}{list.map(g=><section key={g.title} className="rounded-xl border border-emerald-950/70 bg-[linear-gradient(145deg,rgba(15,33,26,.92),rgba(8,23,18,.92))] p-4"><h3 className="text-sm font-semibold text-white">{g.title}</h3><p className="mt-1 text-xs text-slate-500">{g.text}</p><div className="mt-4 flex flex-wrap gap-2">{g.items.map(item=>{const Icon=item.icon??Activity;const supported=supportedActions.has(item.action);return <Button key={item.action} size="sm" variant={item.danger?'destructive':'outline'} disabled={!!busy||!supported} title={!supported?'Bu işlem mevcut agent sürümünde desteklenmiyor veya yetkiniz yok.':undefined} onClick={()=>void run(item)}><Icon className="mr-2 size-4"/>{busy===item.action?'Hazırlanıyor…':item.label}</Button>})}</div>{g.items.some(x=>x.note)&&<p className="mt-3 text-xs text-amber-300">{g.items.find(x=>x.note)?.note}</p>}</section>)}{notice&&<div className="rounded-lg border border-emerald-500/25 bg-emerald-950/25 px-4 py-3 text-xs text-emerald-200">{notice}{last?.id?` · Komut #${last.id}`:''}</div>}</div>
}
