'use client'
import { useEffect, useMemo, useState } from 'react'
import useSWR from 'swr'
import { FileText, RefreshCw, Search, Trash2, UserCog } from 'lucide-react'
import { Button } from '@/components/ui/button'

 type Note={id:string;playerName:string;note:string;authorName:string;createdAt:string}
 type History={id:number;stream:string;line:string;createdAt:string}
 type Data={playerName:string;canManage:boolean;notes:Note[];history:History[]}
async function fetcher(url:string){const r=await fetch(url,{cache:'no-store',headers:{accept:'application/json'}});const t=await r.text();let d:any={};try{d=t?JSON.parse(t):{}}catch{d={error:t}}if(!r.ok)throw new Error(d.error??'Oyuncu moderasyon verisi alınamadı');return d}

export function ServerPlayerModeration({serverId,playerNames,canManage}:{serverId:string;playerNames:string[];canManage:boolean}){
 const [player,setPlayer]=useState(playerNames[0]??'');const [manual,setManual]=useState('');const [note,setNote]=useState('');const [busy,setBusy]=useState(false);const [notice,setNotice]=useState('')
 useEffect(()=>{if(!player&&playerNames[0])setPlayer(playerNames[0])},[player,playerNames])
 const valid=/^[A-Za-z0-9_]{1,16}$/.test(player)
 const key=valid?`/api/player-moderation?serverId=${encodeURIComponent(serverId)}&player=${encodeURIComponent(player)}`:null
 const {data,error,mutate,isLoading}=useSWR<Data>(key,fetcher,{refreshInterval:15000,revalidateOnFocus:true})
 const options=useMemo(()=>[...new Set(playerNames)].sort((a,b)=>a.localeCompare(b,'tr')),[playerNames])
 function chooseManual(){const value=manual.trim();if(!/^[A-Za-z0-9_]{1,16}$/.test(value)){setNotice('Minecraft oyuncu adı 1-16 karakter ve yalnız harf/rakam/_ içermelidir.');return}setPlayer(value);setManual('');setNotice('')}
 async function addNote(){if(!valid||!note.trim()||busy)return;setBusy(true);setNotice('');try{const r=await fetch('/api/player-moderation',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({serverId,playerName:player,note:note.trim()})});const d=await fetcherResponse(r);if(!r.ok)throw new Error(d.error??'Not eklenemedi');setNote('');setNotice('Moderasyon notu kaydedildi.');await mutate()}catch(e){setNotice(e instanceof Error?e.message:'Not eklenemedi')}finally{setBusy(false)}}
 async function removeNote(id:string){if(!confirm('Bu moderasyon notu silinsin mi?'))return;setBusy(true);setNotice('');try{const r=await fetch('/api/player-moderation',{method:'DELETE',headers:{'content-type':'application/json'},body:JSON.stringify({serverId,noteId:id})});const d=await fetcherResponse(r);if(!r.ok)throw new Error(d.error??'Not silinemedi');setNotice('Moderasyon notu silindi.');await mutate()}catch(e){setNotice(e instanceof Error?e.message:'Not silinemedi')}finally{setBusy(false)}}
 return <section className="rounded-xl border border-[#203a55] bg-[#081827] p-4">
  <div className="flex flex-col gap-3 lg:flex-row lg:items-end lg:justify-between"><div><div className="flex items-center gap-2"><UserCog className="size-4 text-sky-300"/><h3 className="text-sm font-semibold text-white">Oyuncu Moderasyon Merkezi</h3></div><p className="mt-1 text-xs text-slate-500">Kalıcı yetkili notları ve gerçek console geçmişi. Ping, güven puanı veya hile riski uydurulmaz.</p></div><Button size="sm" variant="outline" disabled={!valid} onClick={()=>mutate()}><RefreshCw className="mr-1.5 size-3.5"/>Yenile</Button></div>
  <div className="mt-4 grid gap-2 md:grid-cols-[minmax(180px,260px)_minmax(220px,1fr)_auto]">{options.length?<select value={options.includes(player)?player:''} onChange={e=>setPlayer(e.target.value)} className="h-10 rounded-md border border-[#28445f] bg-[#091725] px-3 text-xs text-white"><option value="">Çevrimiçi oyuncu seç</option>{options.map(name=><option key={name} value={name}>{name}</option>)}</select>:<div className="h-10 rounded-md border border-[#28445f] bg-[#091725] px-3 text-xs leading-10 text-slate-500">Çevrimiçi isim listesi yok</div>}<div className="relative"><Search className="absolute left-3 top-3 size-3.5 text-slate-500"/><input value={manual} onChange={e=>setManual(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')chooseManual()}} className="h-10 w-full rounded-md border border-[#28445f] bg-[#091725] pl-9 pr-3 text-xs text-white outline-none" placeholder="Offline oyuncu adı yaz..."/></div><Button onClick={chooseManual} variant="outline">Oyuncuyu Aç</Button></div>
  {!valid?<div className="mt-4 rounded-lg border border-dashed border-[#28445f] p-6 text-center text-xs text-slate-500">Bir oyuncu seçin veya geçerli bir Minecraft oyuncu adı girin.</div>:<div className="mt-4 grid gap-3 xl:grid-cols-2">
   <div className="rounded-lg border border-[#20354d] bg-[#091725] p-3"><div className="flex items-center justify-between"><div><p className="text-xs font-semibold text-white">{player} · Moderasyon notları</p><p className="mt-1 text-[10px] text-slate-500">{data?.notes?.length??0} kayıt</p></div><FileText className="size-4 text-sky-300"/></div>{canManage&&data?.canManage!==false&&<div className="mt-3"><textarea value={note} onChange={e=>setNote(e.target.value)} maxLength={2000} rows={3} className="w-full rounded-md border border-[#28445f] bg-[#07131f] p-2.5 text-xs text-white outline-none" placeholder="Bu oyuncu için yetkili notu ekleyin..."/><div className="mt-2 flex items-center justify-between"><span className="text-[10px] text-slate-600">{note.length}/2000</span><Button size="sm" disabled={busy||!note.trim()} onClick={addNote}>Not Ekle</Button></div></div>}<div className="mt-3 max-h-72 space-y-2 overflow-y-auto">{error?<p className="text-xs text-red-300">{error.message}</p>:isLoading?<p className="text-xs text-slate-500">Yükleniyor...</p>:data?.notes?.length?data.notes.map(row=><div key={row.id} className="rounded-md border border-[#20354d] bg-[#07131f] p-2.5"><div className="flex items-start gap-2"><p className="min-w-0 flex-1 whitespace-pre-wrap text-xs text-slate-300">{row.note}</p>{canManage&&data.canManage&&<button onClick={()=>void removeNote(row.id)} className="text-slate-600 hover:text-red-300" title="Notu sil"><Trash2 className="size-3.5"/></button>}</div><p className="mt-2 text-[10px] text-slate-600">{row.authorName} · {new Date(row.createdAt).toLocaleString('tr-TR')}</p></div>):<p className="text-xs text-slate-500">Bu oyuncu için moderasyon notu yok.</p>}</div></div>
   <div className="rounded-lg border border-[#20354d] bg-[#091725] p-3"><p className="text-xs font-semibold text-white">{player} · Console geçmişi</p><p className="mt-1 text-[10px] text-slate-500">Oyuncu adını içeren son 100 gerçek console kaydı</p><div className="mt-3 max-h-[390px] space-y-1.5 overflow-y-auto">{data?.history?.length?data.history.map(row=><div key={row.id} className="rounded-md border border-[#20354d] bg-[#07131f] px-2.5 py-2"><p className="break-words font-mono text-[10px] leading-4 text-slate-300">{row.line}</p><p className="mt-1 text-[9px] text-slate-600">{new Date(row.createdAt).toLocaleString('tr-TR')} · {row.stream}</p></div>):<p className="text-xs text-slate-500">Bu oyuncu adına ait yüklenmiş console geçmişi bulunamadı.</p>}</div></div>
  </div>}{notice&&<div className="mt-3 rounded-md border border-sky-500/20 bg-sky-500/[.05] px-3 py-2 text-xs text-sky-200">{notice}</div>}
 </section>
}
async function fetcherResponse(r:Response){const t=await r.text();try{return t?JSON.parse(t):{}}catch{return {error:t||`HTTP ${r.status}`}}}