'use client'

import { useEffect, useState } from 'react'
import { BookOpen, Boxes, ChevronRight, FileCog, ImagePlus, Layers3, LifeBuoy, LoaderCircle, Package, Palette, Plus, Server, Settings2, X } from 'lucide-react'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { Input } from '@/components/ui/input'
import { Textarea } from '@/components/ui/textarea'
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs'

type ServerInfo={id:string;name:string;worldName?:string|null;coverImageUrl?:string|null;coverVideoUrl?:string|null;connectionAddress?:string|null;publicHost?:string|null;port:number;playerCount:number;status:string;serverSubtitle?:string|null}
type Props={server:ServerInfo[];selectedId:string;onSelect:(id:string)=>void;onClose:()=>void;onRefresh:()=>void}
type WorldData={templates?:Array<{id:string;name:string;description?:string;available?:boolean}>;runtimeWorlds?:Array<{name:string;active?:boolean}>;canManage?:boolean;runtimeError?:string|null}

const resources=[['mods','Modlar','Minecraft modlarını yükle ve yönet.'],['plugins','Pluginler','Sunucu eklentilerini düzenle.'],['configs','Config','Sunucu ve mod yapılandırmalarını yönet.'],['resourcepacks','Resource Packs','Kaynak paketlerini sunucuya ekle.'],['shaders','Shaderlar','Shader paketlerini yükle ve seç.']]

export function ServerManagementWorkspace({server,selectedId,onSelect,onClose,onRefresh}:Props){
  const current=server.find(item=>item.id===selectedId)??server[0]
  const [section,setSection]=useState('overview')
  const [worlds,setWorlds]=useState<WorldData>({})
  const [worldName,setWorldName]=useState('')
  const [saving,setSaving]=useState(false)
  const [notice,setNotice]=useState('')
  useEffect(()=>{if(!current)return;fetch(`/api/worlds?serverId=${current.id}`,{cache:'no-store'}).then(r=>r.ok?r.json():{}).then(setWorlds).catch(()=>setWorlds({runtimeError:'Dünya verileri alınamadı.'}))},[current?.id])
  if(!current)return null
  const preview=current.coverVideoUrl?<video src={current.coverVideoUrl} autoPlay muted loop playsInline className="absolute inset-0 size-full object-cover opacity-60"/>:current.coverImageUrl?<img src={current.coverImageUrl} alt="" className="absolute inset-0 size-full object-cover opacity-60"/>:null
  async function createWorld(){if(!worldName.trim()||!worlds.templates?.[0])return;setSaving(true);setNotice('');try{const response=await fetch('/api/worlds',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({serverId:current.id,action:'create',worldName:worldName.trim(),templateId:worlds.templates[0].id})});const data=await response.json();setNotice(data.message??data.error??'İşlem tamamlandı');if(response.ok){setWorldName('');onRefresh()}}finally{setSaving(false)}}
  return <div className="fixed inset-0 z-50 overflow-auto bg-[#020706]/90 p-3 backdrop-blur-md sm:p-6"><div className="mx-auto flex min-h-[calc(100vh-1.5rem)] max-w-[1500px] flex-col overflow-hidden rounded-3xl border border-emerald-300/15 bg-[#07100d] text-slate-100 shadow-2xl sm:min-h-[calc(100vh-3rem)]">
    <header className="flex items-center justify-between border-b border-white/10 px-5 py-4"><div><div className="flex items-center gap-2 text-base font-semibold"><span className="size-2 rounded-full bg-emerald-400 shadow-[0_0_12px_#4ade80]"/>BLOCKCTRL Yönetim Merkezi</div><p className="mt-1 text-xs text-slate-500">Sunucu vitrinini, dünyaları ve topluluk içeriklerini tek çalışma alanından yönetin.</p></div><Button variant="ghost" size="sm" onClick={onClose}><X className="mr-1 size-4"/>Kapat</Button></header>
    <div className="grid min-h-0 flex-1 lg:grid-cols-[250px_minmax(0,1fr)]"><aside className="border-b border-white/10 bg-black/10 p-3 lg:border-b-0 lg:border-r"><p className="px-3 pb-2 text-[10px] font-semibold uppercase tracking-[.18em] text-slate-500">Sunucular</p><div className="space-y-1">{server.map(item=><button key={item.id} onClick={()=>onSelect(item.id)} className={`flex w-full items-center gap-3 rounded-xl px-3 py-3 text-left transition ${item.id===current.id?'bg-emerald-400/15 text-emerald-200':'text-slate-400 hover:bg-white/5 hover:text-white'}`}><Server className="size-4"/><span className="min-w-0 flex-1 truncate text-sm font-medium">{item.name}</span><ChevronRight className="size-3"/></button>)}</div><div className="my-4 border-t border-white/10"/><p className="px-3 pb-2 text-[10px] font-semibold uppercase tracking-[.18em] text-slate-500">Yönetim</p><div className="space-y-1">{[['overview','Sunucu görünümü',Palette],['worlds','Dünyalar',Layers3],['information','Bilgilendirme',BookOpen],['support','Destekler',LifeBuoy]].map(([key,label,Icon])=><button key={String(key)} onClick={()=>setSection(String(key))} className={`flex w-full items-center gap-3 rounded-xl px-3 py-3 text-left text-sm transition ${section===key?'bg-white/10 text-white':'text-slate-400 hover:bg-white/5 hover:text-white'}`}><Icon className="size-4"/>{String(label)}</button>)}</div></aside>
    <main className="min-w-0 overflow-y-auto p-4 sm:p-7"><div className="mb-6 flex flex-wrap items-end justify-between gap-3"><div><p className="text-xs uppercase tracking-[.18em] text-emerald-300">Seçili sunucu</p><h1 className="mt-1 text-2xl font-bold tracking-tight">{current.name}</h1><p className="mt-1 text-sm text-slate-500">{current.connectionAddress??`${current.publicHost??'IP bekleniyor'}:${current.port}`} · {current.status}</p></div><div className="rounded-full border border-emerald-400/20 bg-emerald-400/10 px-3 py-1 text-xs text-emerald-200">{current.playerCount} oyuncu</div></div>
      {section==='overview'&&<div className="grid gap-5 xl:grid-cols-[minmax(0,1fr)_360px]"><Card className="overflow-hidden border-white/10 bg-black/20"><div className="relative aspect-[16/8] overflow-hidden bg-gradient-to-br from-emerald-950 to-slate-950">{preview}<div className="absolute inset-0 bg-gradient-to-t from-black/80 via-transparent"/><div className="absolute bottom-5 left-5"><p className="text-xs uppercase tracking-[.18em] text-emerald-300">Canlı vitrin</p><h2 className="mt-2 text-3xl font-black">{current.name}</h2><p className="mt-1 text-slate-300">{current.serverSubtitle??'Sunucu açıklaması ekleyin'}</p></div></div><CardContent className="grid gap-3 p-5 sm:grid-cols-3"><div><p className="text-xs text-slate-500">Durum</p><p className="mt-1 font-semibold">{current.status}</p></div><div><p className="text-xs text-slate-500">Oyuncular</p><p className="mt-1 font-semibold">{current.playerCount}</p></div><div><p className="text-xs text-slate-500">Adres</p><p className="mt-1 truncate font-mono text-sm">{current.connectionAddress??'—'}</p></div></CardContent></Card><Card className="border-white/10 bg-black/20"><CardHeader><CardTitle className="flex items-center gap-2 text-base"><Settings2 className="size-4 text-emerald-300"/>Hızlı yönetim</CardTitle><CardDescription>Sunucunun görünen bilgileri ve medya ayarları.</CardDescription></CardHeader><CardContent className="space-y-3"><Input placeholder="Sunucu açıklaması" defaultValue={current.serverSubtitle??''}/><Input placeholder="Kapak görseli URL'si" defaultValue={current.coverImageUrl??''}/><Button className="w-full" onClick={()=>setNotice('Görünüm ayarları kaydedilmeye hazır.')}><ImagePlus className="mr-2 size-4"/>Kapak fotoğrafı seç</Button></CardContent></Card></div>}
      {section==='worlds'&&<WorkspaceSection title="Dünyalar" description="Dünya türlerini ayarla, yeni dünya oluştur ve sunucu kaynaklarını yönet."><div className="grid gap-3 sm:grid-cols-2">{worlds.runtimeWorlds?.map(world=><Card key={world.name} className="border-white/10 bg-black/20"><CardContent className="flex items-center gap-3 p-4"><Layers3 className="size-4 text-emerald-300"/><div><p className="font-medium">{world.name}</p><p className="text-xs text-slate-500">{world.active?'Aktif dünya':'Hazır dünya'}</p></div></CardContent></Card>)}</div><div className="mt-5 flex flex-wrap gap-2"><Input value={worldName} onChange={event=>setWorldName(event.target.value)} placeholder="Yeni dünya adı"/><Button onClick={createWorld} disabled={saving}>{saving?<LoaderCircle className="mr-2 size-4 animate-spin"/>:<Plus className="mr-2 size-4"/>}Dünya oluştur</Button></div><div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{resources.map(([key,label,description],index)=><Card key={key} className="border-white/10 bg-black/20"><CardContent className="p-4"><div className="mb-3 flex size-9 items-center justify-center rounded-lg bg-emerald-400/10 text-emerald-300">{index===0?<Package className="size-4"/>:index===2?<FileCog className="size-4"/>:<Boxes className="size-4"/>}</div><p className="font-medium">{label}</p><p className="mt-1 text-xs text-slate-500">{description}</p><Button variant="outline" size="sm" className="mt-4">Yönet</Button></CardContent></Card>)}</div>{(worlds.runtimeError||notice)&&<p className="mt-4 text-sm text-amber-300">{notice||worlds.runtimeError}</p>}</WorkspaceSection>}
      {section==='information'&&<WorkspaceSection title="Bilgilendirme" description="Sunucu rehberlerini ve duyuruları bloklar halinde oluşturun."><div className="grid gap-4 lg:grid-cols-[1fr_280px]"><div className="space-y-3"><Input placeholder="Bilgilendirme başlığı"/><Textarea placeholder="Paragraf metni yazın..." rows={6}/><div className="grid gap-3 sm:grid-cols-3"><Button variant="outline"><ImagePlus className="mr-2 size-4"/>Fotoğraf</Button><Button variant="outline">GIF / Görsel</Button><Button variant="outline">Video</Button></div></div><Card className="border-white/10 bg-black/20"><CardHeader><CardTitle className="text-sm">Blok ekle</CardTitle></CardHeader><CardContent className="space-y-2"><Button variant="outline" className="w-full justify-start">Başlık</Button><Button variant="outline" className="w-full justify-start">Renkli yazı</Button><Button variant="outline" className="w-full justify-start">Paragraf</Button><Button variant="outline" className="w-full justify-start">Medya</Button></CardContent></Card></div></WorkspaceSection>}
      {section==='support'&&<WorkspaceSection title="Destekler" description="Topluluğunuzun açabileceği destek türlerini belirleyin."><div className="flex gap-2"><Input placeholder="Örn. Teknik destek, Satın alma, Oyuncu şikayeti"/><Button><Plus className="mr-2 size-4"/>Tür ekle</Button></div><div className="mt-5 grid gap-3 sm:grid-cols-2"><SupportType title="Teknik destek" description="Sunucu bağlantısı ve oyun içi sorunlar"/><SupportType title="Oyuncu şikayeti" description="Oyuncu davranışı ve moderasyon talepleri"/><SupportType title="Satın alma desteği" description="VIP ve mağaza işlemleri"/></div></WorkspaceSection>}
    </main></div></div></div>
}
function WorkspaceSection({title,description,children}:{title:string;description:string;children:React.ReactNode}){return <section><div className="mb-5 flex items-start justify-between gap-4"><div><h2 className="text-xl font-bold">{title}</h2><p className="mt-1 text-sm text-slate-500">{description}</p></div><Button variant="outline" size="sm">Kaydet</Button></div>{children}</section>}
function SupportType({title,description}:{title:string;description:string}){return <Card className="border-white/10 bg-black/20"><CardContent className="flex items-center gap-3 p-4"><LifeBuoy className="size-5 text-amber-300"/><div className="min-w-0 flex-1"><p className="font-medium">{title}</p><p className="text-xs text-slate-500">{description}</p></div><Button variant="ghost" size="sm">Düzenle</Button></CardContent></Card>}
