import { headers } from 'next/headers'
import { NextRequest, NextResponse } from 'next/server'
import { and, desc, eq } from 'drizzle-orm'
import { auth } from '@/lib/auth'
import { db, ensurePanelSchema } from '@/lib/db'
import { websiteFormSubmissions, websites } from '@/lib/db/schema'
import { resolvePanelUser } from '@/lib/db/identity'
function normalizeRole(role:unknown){const value=String(role??'').toLowerCase();return value==='manager'||value==='admin'||value==='guide'||value==='member'?value:'member'}
async function actor(){const session=await auth.api.getSession({headers:await headers()});if(!session?.user)return null;return resolvePanelUser(session.user)}
export async function GET(request:NextRequest){await ensurePanelSchema();const a=await actor();if(!a)return NextResponse.json({error:'Unauthorized'},{status:401});const websiteId=String(request.nextUrl.searchParams.get('websiteId')||'');const site=(await db.select().from(websites).where(eq(websites.id,websiteId)).limit(1))[0];if(!site)return NextResponse.json({error:'Website bulunamadı.'},{status:404});if(normalizeRole(a.role)!=='manager'&&site.userId!==a.id)return NextResponse.json({error:'Yetkiniz yok.'},{status:403});const submissions=await db.select().from(websiteFormSubmissions).where(eq(websiteFormSubmissions.websiteId,site.id)).orderBy(desc(websiteFormSubmissions.createdAt)).limit(200);return NextResponse.json({submissions},{headers:{'Cache-Control':'private, no-store'}})}
export async function POST(request:NextRequest){await ensurePanelSchema();const a=await actor();if(!a)return NextResponse.json({error:'Unauthorized'},{status:401});const body=await request.json().catch(()=>({})) as Record<string,unknown>;const websiteId=String(body.websiteId||''),id=String(body.id||''),status=String(body.status||'read');const site=(await db.select().from(websites).where(eq(websites.id,websiteId)).limit(1))[0];if(!site)return NextResponse.json({error:'Website bulunamadı.'},{status:404});if(normalizeRole(a.role)!=='manager'&&site.userId!==a.id)return NextResponse.json({error:'Yetkiniz yok.'},{status:403});if(!['new','read','archived'].includes(status))return NextResponse.json({error:'Geçersiz form durumu.'},{status:400});const [updated]=await db.update(websiteFormSubmissions).set({status}).where(and(eq(websiteFormSubmissions.id,id),eq(websiteFormSubmissions.websiteId,websiteId))).returning({id:websiteFormSubmissions.id,status:websiteFormSubmissions.status});if(!updated)return NextResponse.json({error:'Form başvurusu bulunamadı.'},{status:404});return NextResponse.json({ok:true,submission:updated})}
